### ISSUE TITLE
summbit-discrete-slider:270 - Uncaught SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by xeruf** [summbit/summbit-web-components#1]
Running some very simple HTML in my browser:
```html
<!DOCTYPE html>
<html>
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 <script src="./summbit-discrete-slider.js"></script>
 <title>somethin</title>
 <style type="text/css">
  html, body {
    width: 100%;
    margin: 0;
    height: 100%;
  }
 </style>
</head>
<body>
<summbit-discrete-slider min="0" max="7" value="3" orientation="left-to-right"></summbit-discrete-slider>
</body>
</html>
```
With the latest js downloaded today, yet I get this in the console of latest Firefox:
```sh
Uncaught SyntaxError: export declarations may only appear at top level of a module
summbit-discrete-slider.js:270
```

**Comment by ackh** [comment]
Each web component is implemented in its own JavaScript module. Hence, in order to use it you need to import it as a module. That would look as follows:

````javascript
<script type="module" src="./summbit-discrete-slider.js"></script>
````

Note the `type` attribute which must be set to `module`. For details check the [docs](https://github.com/summbit/summbit-web-components/blob/master/docs/summbit-discrete-slider.md).

**Comment by xeruf** [comment]
thank you, yes I noticed that too after a bit, finally got it working now :)
